# Generated by Django 3.2.9 on 2022-01-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
